dogs:
  name:doubao
  age:1

people:
  name: liuxinchi
  age: 10
  happy: false
  hobby:
    - 打游戏
    - 看电影
    - 女孩子
  map:
    k1: v1
    k2: v2
    date: 2021/5/28
    dog:
      name: dogs.name
      age: dogs.age

