 spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 592295lxc
    type: com.alibaba.druid.pool.DruidDataSource
