spring:
  datasource:
    url: jdbc:mysql://192.168.232.101:3306/mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 592295lxc
    type: com.alibaba.druid.pool.DruidDataSource